name: Project Work Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Test Pipeline
        run: python 3 ../project/tests.sh