name: Project Work Feedback/Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Check Out 
          uses: actions/checkout@v3
      
        - name: Set-up Node
          uses: actions/setup-node@v3
          with:
              node-version: 'lts/*'
  
          # Install python
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
              python-version: 3.11
  
              # python
        - name: Installing dependencies
          run: |
              python -m pip install --upgrade pip
              pip install SQLAlchemy
              pip install pandas
              pip install openpyxl

      # run Test of pw4
        - name: Run Test Pipeline
          run: sh project/tests.sh